name: Cache Dependencies

on:
  workflow_dispatch:   # allows manual trigger
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Step 3: Cache pip dependencies
      - name: Cache pip dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-97593e5
          restore-keys: cache-97593e5

      # Step 4: Prime cache (must reference the step ID `cache`)
      - name: prime-cache-97593e5
        run: |
          echo "Cache hit? ${{ steps.cache.outputs.cache-hit }}"
